Delete generated asserts, re-enable assert generation during build.

diff --git a/testpack/src/main/resources/ctk b/testpack/src/main/resources/ctk
--- a/testpack/src/main/resources/ctk
+++ b/testpack/src/main/resources/ctk
@@ -1,26 +1,104 @@
-#!/usr/bin/env bash
+#!/bin/bash -e
+# A SHORT DESCRIPTION OF YOUR SCRIPT GOES HERE
+# Run the GA4GH CTK
+###############################################################################
+set -e          # exit on command errors (so you MUST handle exit codes properly!)
+set -E          # pass trap handlers down to subshells
+set -o pipefail # capture fail exit codes in piped commands
+#set -x         # execution tracing debug messages
 
-ctk_tgt_urlRoot="http://192.168.2.115:8000/v0.5.1/"
+# Error handler
+on_err() {
+	echo ">> ERROR: $?"
+	FN=0
+	for LN in "${BASH_LINENO[@]}"; do
+		[ "${FUNCNAME[$FN]}" = "main" ] && break
+		echo ">> ${BASH_SOURCE[$FN]} $LN ${FUNCNAME[$FN]}"
+		FN=$(( FN + 1 ))
+	done
+}
+trap on_err ERR
 
-# TODO expand to all known control properties, export to subshell and run CTK there
+# Exit handler
+declare -a EXIT_CMDS
+add_exit_cmd() { EXIT_CMDS+="$*;  "; }
+on_exit(){ eval "${EXIT_CMDS[@]}"; }
+trap on_exit EXIT
 
-CTKJAR="ctk-testpack-0.5.1-SNAPSHOT.jar"
-TGTDIR="target"
+# Get command info
+CMD_PWD=$(pwd)
+CMD="$0"
+CMD_DIR="$(cd "$(dirname "$CMD")" && pwd -P)"
+
+# Defaults and command line options
+[ "$VERBOSE" ] ||  VERBOSE=
+[ "$DEBUG" ]   ||  DEBUG=
+[ "$CTKJAR" ]  ||  CTKJAR="ctk-testpack-0.5.1-SNAPSHOT.jar"
+[ "$ctk_tgt_urlRoot" ] || ctk_tgt_urlRoot="http://192.168.2.115:8000/v0.5.1/"
+[ "$TGTDIR" ] || TGTDIR="target"
+
+# >>>> PUT OTHER ENV VAR DEFAULTS HERE <<<<
+
+# Basic helpers
+out() { echo "$(date +%Y%m%dT%H%M%SZ): $*"; }
+err() { out "$*" 1>&2; }
+vrb() { [ ! "$VERBOSE" ] || out "$@"; }
+dbg() { [ ! "$DEBUG" ] || err "$@"; }
+die() { err "EXIT: $1" && [ "$2" ] && [ "$2" -ge 0 ] && exit "$2" || exit 1; }
+
+# Show help function to be used below
+show_help() {
+	awk 'NR>1{print} /^(###|$)/{exit}' "$CMD"
+	echo "USAGE: $(basename "$CMD") [arguments]"
+	echo "ARGS:"
+	MSG=$(awk '/^NARGS=-1; while/,/^esac; done/' "$CMD" | sed -e 's/^[[:space:]]*/  /' -e 's/|/, /' -e 's/)//' | grep '^  -')
+	EMSG=$(eval "echo \"$MSG\"")
+	echo "$EMSG"
+}
+
+# Parse command line options (odd formatting to simplify show_help() above)
+NARGS=-1; while [ "$#" -ne "$NARGS" ]; do NARGS=$#; case $1 in
+	# SWITCHES
+	-h|--help)      # This help message
+		show_help; exit 1; ;;
+	-d|--debug)     # Enable debugging messages (implies verbose)
+		DEBUG=$(( DEBUG + 1 )) && VERBOSE="$DEBUG" && shift && echo "#-INFO: DEBUG=$DEBUG (implies VERBOSE=$VERBOSE)"; ;;
+	-v|--verbose)   # Enable verbose messages
+		VERBOSE=$(( VERBOSE + 1 )) && shift && echo "#-INFO: VERBOSE=$VERBOSE"; ;;
+	# PAIRS
+	-t|--thing)     # Set a thing to a value (DEFAULT: $THING)
+		shift && THING="$1" && shift && vrb "#-INFO: THING=$THING"; ;;
+	*)
+		break;
+esac; done
+
+[ "$DEBUG" ]  &&  set -x
+
+###############################################################################
+
+# Validate some things
+#TODO: You will probably want to change this but this is an example of simple params validation
+[ $# -gt 0 -a -z "$THING" ]  &&  THING="$1"  &&  shift
+[ "$THING" ]  ||  die "You must provide some thing!"
+[ $# -eq 0 ]  ||  die "ERROR: Unexpected commands!"
+
+# >>>> PUT YOUR SCRIPT HERE <<<<
 
 # if target/ exists, amend its name
 if [ -d "$TGTDIR" ]; then
-  NEWDIR=$TGTDIR-`date -Iseconds`
-  mv $TGTDIR $NEWDIR
+  NEWDIR=${TGTDIR}-`date -Iseconds`
+  mv ${TGTDIR} $NEWDIR
   # if the just-renamed directory is empty, we can forget it
   if [ "$(ls -A $NEWDIR)" ]; then
-        echo "moved existing results to "$NEWDIR
+        out "moved existing results to "${NEWDIR}
   else
       rmdir $NEWDIR
   fi
 fi
 # if no target/ then create it
-mkdir $TGTDIR
+mkdir ${TGTDIR}
 
 # run the CTK
 # other properties are set in application.properties, log4j2.xml
-java -Dctk.tgt.urlRoot=$ctk_tgt_urlRoot -jar $CTKJAR
+# should use a JAVACMD var to find/use specific JDK?
+java -Dctk.tgt.urlRoot=$ctk_tgt_urlRoot -jar ${CTKJAR}
